drop table if exists sources.accueils_zecs cascade;
drop table if exists sources.aeroports cascade;
drop table if exists sources.aeroports_pistes cascade;
drop table if exists sources.aqrp cascade;
drop table if exists sources.aqcf cascade;
drop table if exists sources.aqcfpn cascade;
drop table if exists sources.barrages cascade;
drop table if exists sources.campings_zecs cascade;
drop table if exists sources.electrique cascade;
drop table if exists sources.inmoa cascade;
drop table if exists sources.parcroutier cascade;
drop table if exists sources.photoradar cascade;
drop table if exists sources.telephone_urg cascade;
drop table if exists sources.terres_autochtones cascade;
drop table if exists sources.villes cascade;

drop table if exists accueils_zecs;
drop table if exists aeroports;
drop table if exists aeroports_pistes;
drop table if exists aqrp;
drop table if exists aqcf;
drop table if exists aqcfpn;
drop table if exists barrages;
drop table if exists campings_zecs;
drop table if exists electrique;
drop table if exists inmoa;
drop table if exists parcroutier;
drop table if exists photoradar;
drop table if exists telephone_urg;
drop table if exists terres_autochtones;
drop table if exists villes;
